import { Component } from '@angular/core';

@Component({
  selector: 'app-input-button-unit',
  standalone: true,
  imports: [],
  templateUrl: './input-button-unit.component.html',
  styleUrl: './input-button-unit.component.scss'
})
export class InputButtonUnitComponent {
  title = 'Andies List'; 
  generateTitle(): string {
    return 'This title was generated by a method.';
  }
  changeTitle(newTitle: string) {
    this.title = newTitle;
  }
  getInputValue(event: Event) {
    return (event.target as HTMLInputElement).value;
  }
}
